propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=localhost;port=3306;dbname=dod
                user: root
                password: p@zzw0rd!
                settings:
                    charset: utf8
